# Generated by Django 4.1.7 on 2023-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavour', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('shape', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('layer', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=300)),
            ],
        ),
    ]
