# Generated by Django 4.1.7 on 2023-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cakes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
