# Generated by Django 4.1.7 on 2023-03-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='rating',
        ),
    ]
