# Generated by Django 4.1.7 on 2023-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_movies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.PositiveIntegerField(default=1800),
        ),
    ]
